[build]
builder = "NIXPACKS"

[deploy]
startCommand = "next start --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
branch = "develop"

[environments.production.variables]
NODE_ENV = "production"
NEXTAUTH_URL = "https://darvayaai-production.up.railway.app"
NEXTAUTH_URL_INTERNAL = "https://darvayaai-production.up.railway.app" 